name: Latest Blog Posts

on:
  schedule:
    - cron: "0 */6 * * *" # 6時間ごとに実行
  workflow_dispatch: # 手動実行も可能

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.classmethod.jp/author/ishii-yuta/feed/"
          max_post_count: 5
          readme_path: "./README.md"
          comment_tag_name: "BLOG-POST-LIST"